language: php

dist: trusty

sudo: false

php:
  - 7.0
  - 7.1

env:
  - DB=postgres

services:
  - postgres

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

before_script:
  - phpenv rehash
  - composer install
  - psql -c 'create database badges;' -U postgres
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"

script:
  - composer cs-check
  - sh -c "vendor/bin/phpunit"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    urls:
      - DeployWebHook
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never

addons:
    code_climate:
        repo_token: CodeClimateTokenForReplacement











